name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get install -y tmux
      - run: cargo install cargo-llvm-cov --locked
      - run: cargo llvm-cov --workspace --lcov --output-path lcov.info
      - uses: coverallsapp/github-action@v2
        with:
          file: lcov.info
